// src/data/trivia/types.ts
// ─────────────────────────────────────────────────────────────────────────────
// The six Trivial-Pursuit-style wedges and the shape of a trivia question.
//
// The question JSON in this folder is GENERATED by tools/convert-trivia.js
// from the raw Open Trivia DB dumps in tools/raw/. Never hand-edit those files
// — to drop a bad question, add its id to tools/blocklist.json and re-run:
//
//   node tools/convert-trivia.js && node src/data/ValidateTrivia.js
//
// WEDGE_IDS must stay in sync with WEDGES in both of those scripts.
//
// Colours are pulled from the existing theme palette so trivia looks native
// to the rest of Sip Happens rather than like a bolted-on second app.
// ─────────────────────────────────────────────────────────────────────────────

import { Colors } from '../../styles/theme';

export const WEDGE_IDS = [
  'geography',
  'entertainment',
  'history',
  'arts',
  'science',
  'sport',
] as const;

export type WedgeId = (typeof WEDGE_IDS)[number];

export interface WedgeDefinition {
  id: WedgeId;
  label: string;
  /** Ionicons glyph name. */
  icon: string;
  color: string;
}

export const WEDGES: Record<WedgeId, WedgeDefinition> = {
  geography: {
    id: 'geography',
    label: 'Geography',
    icon: 'globe',
    color: Colors.tertiary, // cyan
  },
  entertainment: {
    id: 'entertainment',
    label: 'Entertainment',
    icon: 'film',
    color: Colors.secondary, // party pink
  },
  history: {
    id: 'history',
    label: 'History',
    icon: 'hourglass',
    color: Colors.primary, // buzzer yellow
  },
  arts: {
    id: 'arts',
    label: 'Arts & Literature',
    icon: 'color-palette',
    color: Colors.grape, // grape
  },
  science: {
    id: 'science',
    label: 'Science & Nature',
    icon: 'flask',
    color: Colors.lime, // lime
  },
  sport: {
    id: 'sport',
    label: 'Sport & Leisure',
    icon: 'football',
    color: Colors.orange, // orange
  },
};

export const WEDGE_LIST: WedgeDefinition[] = WEDGE_IDS.map(id => WEDGES[id]);

/**
 * `multiple` → 3 distractors (4 options on screen).
 * `boolean`  → 1 distractor  (True / False).
 */
export type TriviaQuestionType = 'multiple' | 'boolean';

export interface TriviaQuestion {
  /** Stable: `<wedge>-<sha1(question)[0..8]>`. Survives re-runs and re-ordering. */
  id: string;
  wedge: WedgeId;
  /**
   * The original Open Trivia DB category, e.g. 'Entertainment: Video Games'.
   * Retained so the wedge mapping can be retuned by re-running the converter
   * rather than re-annotating every question.
   */
  sourceCategory: string;
  type: TriviaQuestionType;
  /** 1 easy · 2 medium · 3 hard — matches the Challenge intensity convention. */
  difficulty: 1 | 2 | 3;
  question: string;
  answer: string;
  distractors: string[];
}
